/**
* OpenAPI Petstore
* This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param mapString 
 * @param mapNumber 
 * @param mapInteger 
 * @param mapBoolean 
 * @param mapArrayInteger 
 * @param mapArrayAnytype 
 * @param mapMapString 
 * @param mapMapAnytype 
 * @param anytype1 
 * @param anytype2 
 * @param anytype3 
 */
@Serializable
data class AdditionalPropertiesClass (
    @SerialName(value = "map_string") val mapString: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    @SerialName(value = "map_number") val mapNumber: kotlin.collections.Map<kotlin.String, kotlin.Double>? = null,
    @SerialName(value = "map_integer") val mapInteger: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,
    @SerialName(value = "map_boolean") val mapBoolean: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null,
    @SerialName(value = "map_array_integer") val mapArrayInteger: kotlin.collections.Map<kotlin.String, kotlin.Array<kotlin.Int>>? = null,
    @SerialName(value = "map_array_anytype") val mapArrayAnytype: kotlin.collections.Map<kotlin.String, kotlin.Array<kotlin.String>>? = null,
    @SerialName(value = "map_map_string") val mapMapString: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, kotlin.String>>? = null,
    @SerialName(value = "map_map_anytype") val mapMapAnytype: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, kotlin.String>>? = null,
    @SerialName(value = "anytype_1") val anytype1: kotlin.String? = null,
    @SerialName(value = "anytype_2") val anytype2: kotlin.String? = null,
    @SerialName(value = "anytype_3") val anytype3: kotlin.String? = null
) 



