/**
* OpenAPI Petstore
* This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param attributeString 
 * @param attributeNumber 
 * @param attributeInteger 
 * @param attributeBoolean 
 * @param wrappedArray 
 * @param nameString 
 * @param nameNumber 
 * @param nameInteger 
 * @param nameBoolean 
 * @param nameArray 
 * @param nameWrappedArray 
 * @param prefixString 
 * @param prefixNumber 
 * @param prefixInteger 
 * @param prefixBoolean 
 * @param prefixArray 
 * @param prefixWrappedArray 
 * @param namespaceString 
 * @param namespaceNumber 
 * @param namespaceInteger 
 * @param namespaceBoolean 
 * @param namespaceArray 
 * @param namespaceWrappedArray 
 * @param prefixNsString 
 * @param prefixNsNumber 
 * @param prefixNsInteger 
 * @param prefixNsBoolean 
 * @param prefixNsArray 
 * @param prefixNsWrappedArray 
 */
@Serializable
data class XmlItem (
    @SerialName(value = "attribute_string") val attributeString: kotlin.String? = null,
    @SerialName(value = "attribute_number") val attributeNumber: kotlin.Double? = null,
    @SerialName(value = "attribute_integer") val attributeInteger: kotlin.Int? = null,
    @SerialName(value = "attribute_boolean") val attributeBoolean: kotlin.Boolean? = null,
    @SerialName(value = "wrapped_array") val wrappedArray: kotlin.Array<kotlin.Int>? = null,
    @SerialName(value = "name_string") val nameString: kotlin.String? = null,
    @SerialName(value = "name_number") val nameNumber: kotlin.Double? = null,
    @SerialName(value = "name_integer") val nameInteger: kotlin.Int? = null,
    @SerialName(value = "name_boolean") val nameBoolean: kotlin.Boolean? = null,
    @SerialName(value = "name_array") val nameArray: kotlin.Array<kotlin.Int>? = null,
    @SerialName(value = "name_wrapped_array") val nameWrappedArray: kotlin.Array<kotlin.Int>? = null,
    @SerialName(value = "prefix_string") val prefixString: kotlin.String? = null,
    @SerialName(value = "prefix_number") val prefixNumber: kotlin.Double? = null,
    @SerialName(value = "prefix_integer") val prefixInteger: kotlin.Int? = null,
    @SerialName(value = "prefix_boolean") val prefixBoolean: kotlin.Boolean? = null,
    @SerialName(value = "prefix_array") val prefixArray: kotlin.Array<kotlin.Int>? = null,
    @SerialName(value = "prefix_wrapped_array") val prefixWrappedArray: kotlin.Array<kotlin.Int>? = null,
    @SerialName(value = "namespace_string") val namespaceString: kotlin.String? = null,
    @SerialName(value = "namespace_number") val namespaceNumber: kotlin.Double? = null,
    @SerialName(value = "namespace_integer") val namespaceInteger: kotlin.Int? = null,
    @SerialName(value = "namespace_boolean") val namespaceBoolean: kotlin.Boolean? = null,
    @SerialName(value = "namespace_array") val namespaceArray: kotlin.Array<kotlin.Int>? = null,
    @SerialName(value = "namespace_wrapped_array") val namespaceWrappedArray: kotlin.Array<kotlin.Int>? = null,
    @SerialName(value = "prefix_ns_string") val prefixNsString: kotlin.String? = null,
    @SerialName(value = "prefix_ns_number") val prefixNsNumber: kotlin.Double? = null,
    @SerialName(value = "prefix_ns_integer") val prefixNsInteger: kotlin.Int? = null,
    @SerialName(value = "prefix_ns_boolean") val prefixNsBoolean: kotlin.Boolean? = null,
    @SerialName(value = "prefix_ns_array") val prefixNsArray: kotlin.Array<kotlin.Int>? = null,
    @SerialName(value = "prefix_ns_wrapped_array") val prefixNsWrappedArray: kotlin.Array<kotlin.Int>? = null
) 



